service: PhoneEmailTest

provider:
  name: aws
  runtime: nodejs14.x
  stage: Prod
  region: us-west-1
  memorySize: 128
  deploymentBucket: 
    name: dev.uw1.linqpal-serverlessdeployment
functions:
  app:
    handler: app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true