service: PhoneEmailTest
provider:
  name: aws
  runtime: nodejs14.x
  stage: Prod
  region: us-west-1
  memorySize: 256
  timeout: 30
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true